### ISSUE TITLE
 cisco.ios.ios_ospfv2 モジュールの例で network オプションの指定の方が異なる

### ISSUE THREAD

**Issue by akira6592** [akira6592/ansible-todo#2]
# cisco.ios.ios_ospfv2 モジュールの例

`state: merged` の例で

```yaml
        network:
          address: 198.51.100.0
          wildcard_bits: 0.0.0.255
          area: 5
```
とあるが、`network` オプションはリストであるべき。

以前、例のま試したときは以下エラーになった
```
argument 'network' is of type <class 'dict'> found in 'config -> processes'. and we were unable to convert to list: <class 'dict'> cannot be converted to a list"
```
